// ADD EMPLOYEES
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS'
export const ADD_EMPLOYEE_LOADING = 'ADD_EMPLOYEE_LOADING'
export const ADD_EMPLOYEE_ERROR = 'ADD_EMPLOYEE_ERROR'
// GET EMPLOYEES
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS'
export const GET_EMPLOYEES_LOADING = 'GET_EMPLOYEES_LOADING'
export const GET_EMPLOYEES_ERROR = 'GET_EMPLOYEES_ERROR'
// GET EMPLOYEE BY ID
export const GET_EMPLOYEE_BY_ID_SUCCESS = 'GET_EMPLOYEE_BY_ID_SUCCESS'
export const GET_EMPLOYEE_BY_ID_LOADING = 'GET_EMPLOYEE_BY_ID_LOADING'
export const GET_EMPLOYEE_BY_ID_ERROR = 'GET_EMPLOYEE_BY_ID_ERROR'
// MODIFY EMPLOYEES
export const EDIT_EMPLOYEE_SUCCESS = 'EDIT_EMPLOYEE_SUCCESS'
export const EDIT_EMPLOYEE_LOADING = 'EDIT_EMPLOYEE_LOADING'
export const EDIT_EMPLOYEE_ERROR = 'EDIT_EMPLOYEE_ERROR'
// DELETE EMPLOYEES
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS'
export const DELETE_EMPLOYEE_LOADING = 'DELETE_EMPLOYEE_LOADING'
export const DELETE_EMPLOYEE_ERROR = 'DELETE_EMPLOYEE_ERROR'
// CLEAR ERROR
export const CLEAR_ERROR = 'CLEAR_ERROR'
