// GET LOGIN
export const GET_LOGIN_PENDING = 'GET_LOGIN_PENDING'
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS'
export const GET_LOGIN_ERROR = 'GET_LOGIN_ERROR'

// SET TOKEN
export const SET_TOKEN = 'SET_TOKEN'

// LOGOUT
export const LOGOUT = 'LOGOUT'
